import { useCallback, useEffect, useMemo, useState } from "react";
import { BrowserRouter, Navigate, NavLink, Route, Routes, useLocation, useNavigate } from "react-router-dom";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { createCategory, createTransaction, deleteCategory, deleteTransaction, getCategories, getTransactions, login, register, updateCategory, updateTransaction } from "./services/api";
import "./App.css";

const money = (value) => new Intl.NumberFormat("tr-TR", { style: "currency", currency: "TRY", maximumFractionDigits: 2 }).format(Number(value) || 0);
const dateText = (value) => new Date(value).toLocaleDateString("tr-TR", { day: "2-digit", month: "short", year: "numeric" });
const colors = ["#6757df", "#12a594", "#f59e0b", "#ef5da8", "#4385f5", "#f46b45"];
const getUser = () => { try { return JSON.parse(localStorage.getItem("user") || sessionStorage.getItem("user")) || {}; } catch { return {}; } };
const uniqueCategories = (list) => {
  const map = new Map();
  list.forEach((item) => {
    const key = item.name.trim().toLocaleLowerCase("tr-TR");
    if (!map.has(key)) map.set(key, { ...item, transactionCount: Number(item.transactionCount) || 0 });
    else map.get(key).transactionCount += Number(item.transactionCount) || 0;
  });
  return [...map.values()];
};

function LegacyAuth({ mode }) {
  const navigate = useNavigate();
  const [form, setForm] = useState({ fullName: "", email: "", password: "" });
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (e) => {
    e.preventDefault(); setBusy(true); setError("");
    try {
      if (mode === "register") { await register(form.fullName.trim(), form.email.trim(), form.password); navigate("/login", { state: { notice: "Hesabın hazır. Şimdi giriş yapabilirsin." } }); }
      else { const data = await login(form.email.trim(), form.password); localStorage.setItem("token", data.token); localStorage.setItem("user", JSON.stringify({ userId: data.userId, fullName: data.fullName, email: data.email })); navigate("/"); }
    } catch (err) { setError(err.message); } finally { setBusy(false); }
  };
  return <div className="auth-shell"><section className="auth-brand"><div className="brand-mark">₺</div><h1>Paran net.<br/>Kararların güçlü.</h1><p>Gelir ve giderlerini tek bakışta gör, finansal düzenini kolayca kur.</p><div className="auth-pills"><span>✓ Gerçek zamanlı özet</span><span>✓ Güvenli hesap</span></div></section><main className="auth-panel"><form className="auth-card" onSubmit={submit}><span className="eyebrow">MONEYTRACK</span><h2>{mode === "register" ? "Hesap oluştur" : "Tekrar hoş geldin"}</h2><p>{mode === "register" ? "Finansal takibine bugün başla." : "Paneline devam etmek için giriş yap."}</p>{error && <div className="alert error">{error}</div>}{mode === "register" && <label>Ad soyad<input required minLength="2" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder="Adın Soyadın" /></label>}<label>E-posta<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="ornek@email.com" /></label><label>Şifre<input required minLength="6" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="En az 6 karakter" /></label><button className="primary full" disabled={busy}>{busy ? "Lütfen bekle..." : mode === "register" ? "Ücretsiz hesap oluştur" : "Giriş yap"}</button><p className="auth-switch">{mode === "register" ? "Zaten hesabın var mı?" : "Henüz hesabın yok mu?"} <NavLink to={mode === "register" ? "/login" : "/register"}>{mode === "register" ? "Giriş yap" : "Kayıt ol"}</NavLink></p></form></main></div>;
}

function Auth({mode}){const navigate=useNavigate(),[form,setForm]=useState({fullName:"",email:"",password:""}),[remember,setRemember]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{if(mode==="register"){await register(form.fullName.trim(),form.email.trim(),form.password);navigate("/login")}else{const data=await login(form.email.trim(),form.password),storage=remember?localStorage:sessionStorage,other=remember?sessionStorage:localStorage;other.removeItem("token");other.removeItem("user");storage.setItem("token",data.token);storage.setItem("user",JSON.stringify({userId:data.userId,fullName:data.fullName,email:data.email}));navigate("/")}}catch(err){setError(err.message)}finally{setBusy(false)}};return <div className="auth-shell"><section className="auth-brand"><div className="brand-mark">₺</div><h1>Paran net.<br/>Kararların güçlü.</h1><p>Gelir ve giderlerini tek bakışta gör, finansal düzenini kolayca kur.</p><div className="auth-pills"><span>✓ Gerçek zamanlı özet</span><span>✓ Güvenli hesap</span></div></section><main className="auth-panel"><form className="auth-card" onSubmit={submit}><span className="eyebrow">KAYIT DEFTERİM</span><h2>{mode==="register"?"Hesap oluştur":"Tekrar hoş geldin"}</h2><p>{mode==="register"?"Finansal takibine bugün başla.":"Kayıt Defterime giriş yap."}</p>{error&&<div className="alert error">{error}</div>}{mode==="register"&&<label>Ad soyad<input required minLength="2" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder="Adın Soyadın"/></label>}<label>E-posta<input required type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="ornek@email.com"/></label><label>Şifre<input required minLength="6" type="password" autoComplete={mode==="register"?"new-password":"current-password"} value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="En az 6 karakter"/></label>{mode==="login"&&<label className="remember-me"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span><b>Beni hatırla</b><small>Tarayıcıyı kapatsan da oturumun açık kalsın.</small></span></label>}<button className="primary full" disabled={busy}>{busy?"Lütfen bekle...":mode==="register"?"Ücretsiz hesap oluştur":"Giriş yap"}</button><p className="auth-switch">{mode==="register"?"Zaten hesabın var mı?":"Henüz hesabın yok mu?"} <NavLink to={mode==="register"?"/login":"/register"}>{mode==="register"?"Giriş yap":"Kayıt ol"}</NavLink></p></form></main></div>}

void LegacyAuth;
function AppLayoutInternal() {
  const navigate = useNavigate(); const location = useLocation(); const user = getUser();
  const [items,setItems]=useState([]), [categories,setCategories]=useState([]), [loading,setLoading]=useState(true), [error,setError]=useState(""), [menu,setMenu]=useState(false), [notices,setNotices]=useState(false), [search,setSearch]=useState("");
  const load = useCallback(async()=>{ setLoading(true); setError(""); try { const [a,b]=await Promise.all([getTransactions(),getCategories()]); setItems(Array.isArray(a)?a:[]); setCategories(uniqueCategories(Array.isArray(b)?b:[])); } catch(e){setError(e.message);} finally{setLoading(false);} },[]);
  useEffect(()=>{load();},[load]);
  useEffect(()=>{const expired=()=>navigate("/login"); window.addEventListener("auth-expired",expired); return()=>window.removeEventListener("auth-expired",expired);},[navigate]);
  useEffect(()=>setMenu(false),[location.pathname]);
  const logout=()=>{localStorage.removeItem("token");localStorage.removeItem("user");sessionStorage.removeItem("token");sessionStorage.removeItem("user");window.location.replace("/login");};
  const pageNames={"/":"Genel Bakış","/islemler":"İşlemler","/istatistikler":"İstatistikler","/kategoriler":"Kategoriler"};
  const context={items,categories,loading,error,reload:load,search};
  return <div className="app-shell"><aside className={`sidebar ${menu?"open":""}`}><div className="logo"><span>₺</span><div><b>MoneyTrack</b><small>Finans yönetimi</small></div></div><nav>{[["/","⌂","Ana Sayfa"],["/islemler","↕","İşlemler"],["/istatistikler","⌁","İstatistikler"],["/kategoriler","▦","Kategoriler"]].map(([to,icon,label])=><NavLink key={to} to={to} end={to==="/"}><i>{icon}</i>{label}</NavLink>)}</nav><div className="sidebar-user"><div className="avatar">{user.fullName?.[0]?.toUpperCase()||"K"}</div><div><b>{user.fullName||"Kullanıcı"}</b><small>{user.email}</small></div><button onClick={logout} title="Çıkış yap">↪</button></div></aside>{menu&&<button className="scrim" onClick={()=>setMenu(false)} />}
  <main className="main"><header><button className="menu-btn" onClick={()=>setMenu(true)}>☰</button><div><span className="eyebrow">MONEYTRACK</span><h2>{pageNames[location.pathname]||"MoneyTrack"}</h2></div><div className="header-actions"><label className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="İşlem ara..." /></label><div className="notice-wrap"><button className="icon-btn" onClick={()=>setNotices(!notices)}>♢<em>{items.length?1:0}</em></button>{notices&&<div className="notice-panel"><b>Bildirimler</b><p>{items.length ? `Toplam ${items.length} işlemin bulunuyor.` : "İlk işlemini ekleyerek başla."}</p><button onClick={()=>{setNotices(false);navigate("/islemler")}}>İşlemlere git →</button></div>}</div><div className="profile"><div className="avatar">{user.fullName?.[0]?.toUpperCase()||"K"}</div><div><b>{user.fullName||"Kullanıcı"}</b><small>Finans paneli</small></div></div></div></header>{error&&<div className="alert error">{error} <button onClick={load}>Tekrar dene</button></div>}<Routes><Route index element={<Dashboard {...context} user={user}/>} /><Route path="islemler" element={<Transactions {...context}/>} /><Route path="istatistikler" element={<Statistics {...context}/>} /><Route path="kategoriler" element={<Categories {...context}/>} /><Route path="*" element={<Navigate to="/"/>}/></Routes></main></div>;
}

function LegacyDashboard({items,loading,user,search}) {
  const storageKey = `opening-balance-${user.userId || user.email || "guest"}`;
  const [openingBalance,setOpeningBalance] = useState(() => Number(localStorage.getItem(storageKey)) || 0);
  const [balanceInput,setBalanceInput] = useState(() => String(Number(localStorage.getItem(storageKey)) || ""));
  const income=items.filter(x=>x.isIncome).reduce((s,x)=>s+Number(x.amount),0);
  const expense=items.filter(x=>!x.isIncome).reduce((s,x)=>s+Number(x.amount),0);
  const balance=openingBalance+income-expense;
  const filteredItems=items.filter(x=>`${x.description} ${x.category}`.toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR")));
  const saveBalance=(e)=>{e.preventDefault();const value=Number(balanceInput)||0;localStorage.setItem(storageKey,String(value));setOpeningBalance(value)};
  const monthly=useMemo(()=>{const map={};items.forEach(x=>{const d=new Date(x.date),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;map[k]??={key:k,name:d.toLocaleDateString("tr-TR",{month:"short"}),gelir:0,gider:0};map[k][x.isIncome?"gelir":"gider"]+=Number(x.amount)});return Object.values(map).sort((a,b)=>a.key.localeCompare(b.key)).slice(-6)},[items]);
  const cat=useMemo(()=>Object.values(items.filter(x=>!x.isIncome).reduce((a,x)=>{const n=x.category||"Diğer";a[n]??={name:n,value:0};a[n].value+=Number(x.amount);return a},{})),[items]);
  if(loading)return <Loading/>;
  if(search.trim()) return <>
    <section className="page-title"><div><h1>Arama sonuçları</h1><p>“{search}” için bulunan işlemler.</p></div><NavLink className="primary" to="/islemler">Tüm işlemler</NavLink></section>
    <TransactionList items={filteredItems} title={`${filteredItems.length} işlem bulundu`}/>
  </>;
  return <>
    <section className="welcome"><div><h1>Merhaba, {user.fullName?.split(" ")[0]||"Kullanıcı"} <span>👋</span></h1><p>Finansal durumunun güncel özeti burada.</p></div><NavLink className="primary" to="/islemler">+ Yeni işlem</NavLink></section>
    <form className="balance-setter" onSubmit={saveBalance}><div><span>Başlangıç bakiyesi</span><small>Mevcut paranı gir; gelir ve giderler bunun üzerine hesaplanır.</small></div><label><span>₺</span><input type="number" step="0.01" value={balanceInput} onChange={e=>setBalanceInput(e.target.value)} placeholder="28.000"/></label><button className="primary">Bakiyeyi kaydet</button></form>
    <section className="metric-grid"><Metric icon="◈" label="Güncel bakiye" value={money(balance)} tone="purple"/><Metric icon="↗" label="Toplam gelir" value={money(income)} tone="green"/><Metric icon="↘" label="Toplam gider" value={money(expense)} tone="red"/></section>
    <section className="dashboard-grid">
      <div className="stack"><Card title="Aylık hareket" subtitle="Son altı ayın gelir ve gider karşılaştırması"><ResponsiveContainer width="100%" height={280}><AreaChart data={monthly}><CartesianGrid strokeDasharray="4 4" vertical={false}/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip formatter={money}/><Area type="monotone" dataKey="gider" stroke="#7057d9" fill="#eee9ff" strokeWidth={3}/><Area type="monotone" dataKey="gelir" stroke="#17a88b" fill="transparent" strokeWidth={3}/></AreaChart></ResponsiveContainer></Card></div>
      <div className="stack"><Card title="Gider dağılımı" subtitle="Kategorilere göre"><ResponsiveContainer width="100%" height={205}><PieChart><Pie data={cat} dataKey="value" innerRadius={56} outerRadius={82} paddingAngle={4}>{cat.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={money}/></PieChart></ResponsiveContainer><div className="legend">{cat.slice(0,5).map((x,i)=><span key={x.name}><i style={{background:colors[i%colors.length]}}/>{x.name}<b>{money(x.value)}</b></span>)}</div></Card></div>
      <div className="health-row"><Card title="Finansal sağlık" subtitle="Gelir-gider dengesi"><div className="health"><strong>{income ? Math.max(0,Math.round(((income-expense)/income)*100)) : 0}%</strong><p>Gelirinden kalan oran</p><div className="progress"><i style={{width:`${income?Math.max(0,Math.min(100,((income-expense)/income)*100)):0}%`}}/></div></div></Card></div>
      <div className="transactions-row"><TransactionList items={filteredItems.slice(0,5)} title={search?`Arama sonuçları (${filteredItems.length})`:"Son işlemler"}/></div>
    </section>
  </>;
}

void LegacyDashboard;
function Dashboard({items,loading,user,search}) {
  const userKey=user.userId||user.email||"guest",budgetKey=`monthly-budget-${userKey}`,balanceKey=`opening-balance-${userKey}`;
  const [budget,setBudget]=useState(()=>Number(localStorage.getItem(budgetKey))||10000),[budgetInput,setBudgetInput]=useState(()=>localStorage.getItem(budgetKey)||"10000");
  const [opening,setOpening]=useState(()=>Number(localStorage.getItem(balanceKey))||0),[openingInput,setOpeningInput]=useState(()=>localStorage.getItem(balanceKey)||"");
  const income=items.filter(x=>x.isIncome).reduce((s,x)=>s+Number(x.amount),0),expense=items.filter(x=>!x.isIncome).reduce((s,x)=>s+Number(x.amount),0),balance=opening+income-expense;
  const now=new Date(),monthExpense=items.filter(x=>{const d=new Date(x.date);return !x.isIncome&&d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).reduce((s,x)=>s+Number(x.amount),0),budgetRate=budget?Math.min(100,monthExpense/budget*100):0;
  const filtered=items.filter(x=>`${x.description} ${x.category}`.toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR")));
  const cat=useMemo(()=>Object.values(items.filter(x=>!x.isIncome).reduce((a,x)=>{a[x.category]??={name:x.category,value:0};a[x.category].value+=Number(x.amount);return a},{})).sort((a,b)=>b.value-a.value),[items]);
  const save=(e,k,v,setter)=>{e.preventDefault();const n=Math.max(0,Number(v)||0);localStorage.setItem(k,String(n));setter(n)};
  if(loading)return <Loading/>;if(search.trim())return <><section className="page-title"><div><h1>Arama sonuçları</h1><p>“{search}” için bulunan işlemler.</p></div></section><TransactionList items={filtered} title={`${filtered.length} işlem bulundu`}/></>;
  return <><section className="welcome"><div><h1>Merhaba, {user.fullName?.split(" ")[0]||"Kullanıcı"} 👋</h1><p>Finansal durumunun güncel özeti burada.</p></div><NavLink className="primary" to="/islemler">+ Yeni işlem</NavLink></section><section className="metric-grid colorful"><Metric icon="◈" label="Güncel bakiye" value={money(balance)} tone="purple"/><Metric icon="↗" label="Toplam gelir" value={money(income)} tone="green"/><Metric icon="↘" label="Toplam gider" value={money(expense)} tone="red"/></section><section className="control-grid"><form className="control-card" onSubmit={e=>save(e,balanceKey,openingInput,setOpening)}><div><b>Başlangıç bakiyesi</b><small>Mevcut paran</small></div><label>₺<input type="number" value={openingInput} onChange={e=>setOpeningInput(e.target.value)}/></label><button>Kaydet</button></form><form className="control-card budget" onSubmit={e=>save(e,budgetKey,budgetInput,setBudget)}><div><b>Aylık bütçe</b><small>{money(monthExpense)} / {money(budget)}</small></div><div className="mini-progress"><i style={{width:`${budgetRate}%`}}/></div><label>₺<input type="number" value={budgetInput} onChange={e=>setBudgetInput(e.target.value)}/></label><button>Güncelle</button></form></section><section className="insight-grid"><div><span>◎</span><p><small>En yüksek harcama</small><b>{cat[0]?.name||"Veri yok"}</b></p><strong>{cat[0]?money(cat[0].value):"—"}</strong></div><div><span>◔</span><p><small>Bütçe kullanımı</small><b>{Math.round(budgetRate)}% kullanıldı</b></p><strong className={budgetRate>85?"warn":"good"}>{budgetRate>85?"Limite yakın":"Kontrol altında"}</strong></div><div><span>✦</span><p><small>Akıllı öneri</small><b>{expense>income?"Giderler geliri aşıyor":"Finansal dengen iyi"}</b></p><strong>{items.length} kayıt</strong></div></section><section className="dashboard-grid"><div className="stack"><TransactionList items={items.slice(0,5)}/></div><div className="stack"><Card title="Gider dağılımı" subtitle="Kategorilere göre"><ResponsiveContainer width="100%" height={210}><PieChart><Pie data={cat} dataKey="value" innerRadius={58} outerRadius={84}>{cat.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={money}/></PieChart></ResponsiveContainer><div className="legend">{cat.slice(0,5).map((x,i)=><span key={x.name}><i style={{background:colors[i%colors.length]}}/>{x.name}<b>{money(x.value)}</b></span>)}</div></Card><Card title="Finansal sağlık"><div className="health"><strong>{income?Math.max(0,Math.round((income-expense)/income*100)):0}%</strong><p>Gelirinden kalan oran</p><div className="progress"><i style={{width:`${income?Math.max(0,Math.min(100,(income-expense)/income*100)):0}%`}}/></div></div></Card></div></section></>;
}

function Transactions(props){return <EnhancedTransactions {...props}/>}
function EnhancedTransactions({items,categories,loading,reload,search}){
 const [type,setType]=useState("all"),[category,setCategory]=useState("all"),[period,setPeriod]=useState("all");const now=new Date();
 const filtered=items.filter(x=>{const d=new Date(x.date);return `${x.description} ${x.category}`.toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR"))&&(type==="all"||(type==="income"?x.isIncome:!x.isIncome))&&(category==="all"||String(x.categoryId)===category)&&(period==="all"||(period==="month"&&d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear())||(period==="year"&&d.getFullYear()===now.getFullYear()))});
 return <><div className="filter-bar"><select value={type} onChange={e=>setType(e.target.value)}><option value="all">Tüm türler</option><option value="income">Gelirler</option><option value="expense">Giderler</option></select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Tüm kategoriler</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="all">Tüm tarihler</option><option value="month">Bu ay</option><option value="year">Bu yıl</option></select><b>{filtered.length} sonuç</b></div><LegacyTransactions items={filtered} categories={categories} loading={loading} reload={reload} search=""/></>;
}

function LegacyTransactions({items,categories,loading,reload,search}) {
  const empty={description:"",amount:"",isIncome:false,categoryId:""}; const [form,setForm]=useState(empty),[editing,setEditing]=useState(null),[message,setMessage]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!form.categoryId&&categories[0])setForm(x=>({...x,categoryId:String(categories[0].id)}));},[categories,form.categoryId]);
  const submit=async e=>{e.preventDefault();setBusy(true);setError("");try{const payload={...form,amount:Number(form.amount),categoryId:Number(form.categoryId)};if(editing)await updateTransaction(editing,payload);else await createTransaction(payload);setMessage(editing?"İşlem güncellendi.":"İşlem eklendi.");setEditing(null);setForm({...empty,categoryId:String(categories[0]?.id||"")});await reload();}catch(e){setError(e.message)}finally{setBusy(false)}};
  const edit=x=>{setEditing(x.id);setForm({description:x.description,amount:x.amount,isIncome:x.isIncome,categoryId:String(x.categoryId)});window.scrollTo({top:0,behavior:"smooth"})};
  const remove=async id=>{if(!confirm("Bu işlemi silmek istiyor musun?"))return;try{await deleteTransaction(id);setMessage("İşlem silindi.");await reload()}catch(e){setError(e.message)}};
  const filtered=items.filter(x=>`${x.description} ${x.category}`.toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR")));
  return <><section className="page-title"><div><h1>İşlemler</h1><p>Gelir ve gider kayıtlarını yönet.</p></div></section><Card title={editing?"İşlemi düzenle":"Yeni işlem ekle"} subtitle="Bilgileri eksiksiz gir"><form className="form-grid" onSubmit={submit}>{error&&<div className="alert error span">{error}</div>}{message&&<div className="alert success span">{message}</div>}<label>Açıklama<input required minLength="2" maxLength="120" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Örn. Market alışverişi"/></label><label>Tutar<input required type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="0,00"/></label><label>İşlem türü<select value={String(form.isIncome)} onChange={e=>setForm({...form,isIncome:e.target.value==="true"})}><option value="false">Gider</option><option value="true">Gelir</option></select></label><label>Kategori<select required value={form.categoryId} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Kategori seç</option>{categories.map(x=><option key={x.id} value={x.id}>{x.icon} {x.name}</option>)}</select></label><div className="form-actions span">{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setForm({...empty,categoryId:String(categories[0]?.id||"")})}}>Vazgeç</button>}<button className="primary" disabled={busy||!categories.length}>{busy?"Kaydediliyor...":editing?"Değişiklikleri kaydet":"+ İşlem ekle"}</button></div></form></Card>{loading?<Loading/>:<TransactionList items={filtered} actions={{edit,remove}} title={`Tüm işlemler (${filtered.length})`}/>}</>;
}

function Statistics({items,loading}) { const income=items.filter(x=>x.isIncome).reduce((s,x)=>s+Number(x.amount),0),expense=items.filter(x=>!x.isIncome).reduce((s,x)=>s+Number(x.amount),0);const cat=Object.values(items.filter(x=>!x.isIncome).reduce((a,x)=>{a[x.category]??={name:x.category,value:0};a[x.category].value+=Number(x.amount);return a},{})).sort((a,b)=>b.value-a.value);if(loading)return <Loading/>;return <><section className="page-title"><div><h1>İstatistikler</h1><p>Harcama alışkanlıklarını verilerle keşfet.</p></div></section><section className="metric-grid"><Metric label="Tasarruf oranı" value={`${income?Math.round(((income-expense)/income)*100):0}%`} icon="◎" tone="purple"/><Metric label="Ortalama işlem" value={money(items.length?(income+expense)/items.length:0)} icon="≋" tone="green"/><Metric label="İşlem sayısı" value={items.length} icon="#" tone="red"/></section><section className="two-grid"><Card title="Kategori analizi" subtitle="Toplam gider içindeki pay"><ResponsiveContainer width="100%" height={320}><PieChart><Pie data={cat} dataKey="value" nameKey="name" innerRadius={75} outerRadius={115} paddingAngle={3}>{cat.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={money}/></PieChart></ResponsiveContainer></Card><Card title="En çok harcananlar" subtitle="Kategori sıralaması"><div className="ranking">{cat.length?cat.map((x,i)=><div key={x.name}><span><i style={{background:colors[i%colors.length]}}>{i+1}</i>{x.name}</span><b>{money(x.value)}</b><small style={{width:`${expense?x.value/expense*100:0}%`}}/></div>):<Empty text="Analiz için henüz gider yok."/>}</div></Card></section></> }

function Categories({categories,reload}) {const [form,setForm]=useState({name:"",icon:"📦"}),[editing,setEditing]=useState(null),[error,setError]=useState("");const submit=async e=>{e.preventDefault();setError("");try{editing?await updateCategory(editing,form):await createCategory(form);setEditing(null);setForm({name:"",icon:"📦"});await reload()}catch(e){setError(e.message)}};const remove=async id=>{if(!confirm("Bu kategoriyi silmek istiyor musun?"))return;try{await deleteCategory(id);await reload()}catch(e){setError(e.message)}};return <><section className="page-title"><div><h1>Kategoriler</h1><p>İşlemlerini düzenli tutan başlıkları yönet.</p></div></section><section className="category-layout"><Card title={editing?"Kategoriyi düzenle":"Yeni kategori"} subtitle="Kısa ve anlaşılır bir ad seç"><form className="category-form" onSubmit={submit}>{error&&<div className="alert error">{error}</div>}<label>Simge<input required maxLength="12" value={form.icon} onChange={e=>setForm({...form,icon:e.target.value})}/></label><label>Kategori adı<input required minLength="2" maxLength="40" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Örn. Ulaşım"/></label><button className="primary">{editing?"Güncelle":"Kategori ekle"}</button>{editing&&<button type="button" className="secondary" onClick={()=>{setEditing(null);setForm({name:"",icon:"📦"})}}>Vazgeç</button>}</form></Card><Card title={`Kategoriler (${categories.length})`} subtitle="Kullanımdaki kategoriler silinemez"><div className="category-list">{categories.map((x,i)=><div key={x.id}><span className="category-icon" style={{background:`${colors[i%colors.length]}18`,color:colors[i%colors.length]}}>{x.icon}</span><span><b>{x.name}</b><small>{x.transactionCount} işlem</small></span><div><button onClick={()=>{setEditing(x.id);setForm({name:x.name,icon:x.icon})}}>Düzenle</button><button className="danger" onClick={()=>remove(x.id)}>Sil</button></div></div>)}</div></Card></section></>}

function Metric({icon,label,value,tone}){return <div className="metric"><i className={tone}>{icon}</i><div><span>{label}</span><strong>{value}</strong></div></div>}
function BasicCard({title,subtitle,children}){return <section className="card"><div className="card-head"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div></div>{children}</section>}
function Card({title,subtitle,children}){return title==="Finansal sağlık"?<SelectedSavingsGoals/>:<BasicCard title={title} subtitle={subtitle}>{children}</BasicCard>}
function LegacyTransactionList({items,title="Son işlemler",actions}){return <Card title={title} subtitle="En güncel kayıtlar"><div className="transaction-list">{items.length?items.map(x=><div className="transaction" key={x.id}><span className={`tx-icon ${x.isIncome?"in":"out"}`}>{x.categoryIcon||x.category?.[0]||"₺"}</span><div className="tx-main"><b>{x.description}</b><small>{x.category} · {dateText(x.date)}</small></div><strong className={x.isIncome?"amount-in":"amount-out"}>{x.isIncome?"+":"−"}{money(x.amount)}</strong>{actions&&<div className="tx-actions"><button onClick={()=>actions.edit(x)}>Düzenle</button><button className="danger" onClick={()=>actions.remove(x.id)}>Sil</button></div>}</div>):<Empty text="Henüz işlem bulunmuyor."/>}</div></Card>}
function CoreTransactionList(props){if(!props.items.length&&(!props.title||props.title==="Son işlemler"))return <BasicCard title="Başlangıç rehberi" subtitle="Kayıt Defterim'i üç adımda kullanmaya başla"><div className="onboarding"><div><i>1</i><b>Bakiyeni belirle</b><small>Mevcut nakit tutarını kaydet.</small></div><div><i>2</i><b>İlk işlemi ekle</b><small>Gelir veya gider kaydı oluştur.</small></div><div><i>3</i><b>Hedefini oluştur</b><small>Birikimini düzenli takip et.</small></div></div><NavLink className="primary guide-button" to="/islemler">İlk işlemi ekle →</NavLink></BasicCard>;return <LegacyTransactionList {...props}/>}
function SavingsGoal(){const user=getUser(),key=`saving-goal-${user.userId||user.email||"guest"}`,[saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))||{name:"Yeni telefon",target:30000,current:0}}catch{return{name:"Yeni telefon",target:30000,current:0}}}),[form,setForm]=useState(saved);const rate=Math.min(100,saved.target?Math.round(saved.current/saved.target*100):0),submit=e=>{e.preventDefault();const value={name:form.name.trim()||"Birikim hedefim",target:Math.max(0,Number(form.target)||0),current:Math.max(0,Number(form.current)||0)};localStorage.setItem(key,JSON.stringify(value));setSaved(value)};return <BasicCard title="Birikim hedefim" subtitle="Hayaline ne kadar yaklaştığını takip et"><div className="goal-layout"><div className="goal-ring" style={{"--goal":`${rate*3.6}deg`}}><div><strong>%{rate}</strong><small>{money(saved.current)}</small></div></div><div className="goal-info"><span>Hedef</span><h3>{saved.name}</h3><p><b>{money(saved.current)}</b> birikti · {money(Math.max(0,saved.target-saved.current))} kaldı</p><div className="goal-bar"><i style={{width:`${rate}%`}}/></div></div></div><form className="goal-form" onSubmit={submit}><input aria-label="Hedef adı" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Örn. Telefon"/><input aria-label="Hedef tutarı" type="number" value={form.target} onChange={e=>setForm({...form,target:e.target.value})} placeholder="Hedef ₺"/><input aria-label="Biriken tutar" type="number" value={form.current} onChange={e=>setForm({...form,current:e.target.value})} placeholder="Biriken ₺"/><button>Kaydet</button></form></BasicCard>}
function CurrencyInput({value,onChange,placeholder,label}){const formatted=value===""?"":new Intl.NumberFormat("tr-TR",{maximumFractionDigits:0}).format(Number(value)||0);return <label className="currency-field"><span>₺</span><input aria-label={label} inputMode="numeric" value={formatted} onChange={e=>onChange(e.target.value.replace(/\D/g,""))} placeholder={placeholder}/></label>}
function FormattedSavingsGoal(){const user=getUser(),key=`saving-goal-${user.userId||user.email||"guest"}`,[saved,setSaved]=useState(()=>{try{return JSON.parse(localStorage.getItem(key))||{name:"Yeni telefon",target:30000,current:0}}catch{return{name:"Yeni telefon",target:30000,current:0}}}),[form,setForm]=useState(()=>({name:saved.name,target:String(saved.target||""),current:String(saved.current||"")}));const rate=Math.min(100,saved.target?Math.round(saved.current/saved.target*100):0);const submit=e=>{e.preventDefault();const value={name:form.name.trim()||"Birikim hedefim",target:Number(form.target)||0,current:Number(form.current)||0};localStorage.setItem(key,JSON.stringify(value));setSaved(value)};return <BasicCard title="Birikim hedefim" subtitle="Hayaline ne kadar yaklaştığını takip et"><div className="goal-layout"><div className="goal-ring" style={{"--goal":`${rate*3.6}deg`}}><div><strong>%{rate}</strong><small>{money(saved.current)}</small></div></div><div className="goal-info"><span>Hedef</span><h3>{saved.name}</h3><p><b>{money(saved.current)}</b> birikti · {money(Math.max(0,saved.target-saved.current))} kaldı</p><div className="goal-bar"><i style={{width:`${rate}%`}}/></div></div></div><form className="goal-form formatted" onSubmit={submit}><input aria-label="Hedef adı" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Örn. Telefon"/><CurrencyInput label="Hedef tutarı" value={form.target} onChange={v=>setForm({...form,target:v})} placeholder="30.000"/><CurrencyInput label="Biriken tutar" value={form.current} onChange={v=>setForm({...form,current:v})} placeholder="12.000"/><button>Kaydet</button></form></BasicCard>}
function SavingsGoals(){const user=getUser(),key=`saving-goals-${user.userId||user.email||"guest"}`,[goals,setGoals]=useState(()=>{try{const a=JSON.parse(localStorage.getItem(key));return Array.isArray(a)?a:[]}catch{return[]}}),[showForm,setShowForm]=useState(false),[draft,setDraft]=useState({name:"",target:""}),[adds,setAdds]=useState({});const persist=list=>{setGoals(list);localStorage.setItem(key,JSON.stringify(list))},create=e=>{e.preventDefault();if(!draft.name.trim()||!Number(draft.target))return;persist([...goals,{id:Date.now(),name:draft.name.trim(),target:Number(draft.target),current:0}]);setDraft({name:"",target:""});setShowForm(false)},add=(id)=>{const amount=Number(adds[id])||0;if(amount<=0)return;persist(goals.map(g=>g.id===id?{...g,current:g.current+amount}:g));setAdds({...adds,[id]:""})},remove=id=>{if(confirm("Bu hedef silinsin mi?"))persist(goals.filter(g=>g.id!==id))};return <BasicCard title="Birikim hedeflerim" subtitle="Birden fazla hedef oluştur ve ilerlemeni takip et"><div className="goals-toolbar"><span>{goals.length} aktif hedef</span><button className="primary" onClick={()=>setShowForm(!showForm)}>+ Yeni hedef ekle</button></div>{showForm&&<form className="new-goal-form" onSubmit={create}><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Hedef adı · Örn. Telefon"/><CurrencyInput label="Hedef tutarı" value={draft.target} onChange={v=>setDraft({...draft,target:v})} placeholder="30.000"/><button>Hedefi oluştur</button></form>}<div className="goals-list">{goals.length?goals.map(g=>{const rate=Math.min(100,g.target?Math.round(g.current/g.target*100):0);return <article className="goal-item" key={g.id}><div className="goal-ring small" style={{"--goal":`${rate*3.6}deg`}}><div><strong>%{rate}</strong><small>{money(g.current)}</small></div></div><div className="goal-info"><span>HEDEF</span><h3>{g.name}</h3><p><b>{money(g.current)}</b> birikti · {money(Math.max(0,g.target-g.current))} kaldı</p><div className="goal-bar"><i style={{width:`${rate}%`}}/></div><div className="contribution"><CurrencyInput label="Birikime eklenecek tutar" value={adds[g.id]||""} onChange={v=>setAdds({...adds,[g.id]:v})} placeholder="Biriken para ekle"/><button onClick={()=>add(g.id)}>Ekle</button><button className="delete-goal" onClick={()=>remove(g.id)}>Sil</button></div></div></article>}):<div className="goal-empty"><span>◎</span><b>Henüz birikim hedefin yok</b><small>Telefon, tatil veya ev gibi hedeflerini ekleyebilirsin.</small></div>}</div></BasicCard>}
function TransactionList(props){const isDashboard=!props.title||props.title==="Son işlemler";return <>{<CoreTransactionList {...props}/>} {isDashboard&&<MonthlyOverviewV2 items={props.items}/>}</>}
function FinancialOverview({items}){const data=useMemo(()=>{const months=[];for(let i=5;i>=0;i--){const d=new Date();d.setMonth(d.getMonth()-i);months.push({key:`${d.getFullYear()}-${d.getMonth()}`,name:d.toLocaleDateString("tr-TR",{month:"short"}),gelir:0,gider:0})}items.forEach(x=>{const d=new Date(x.date),row=months.find(m=>m.key===`${d.getFullYear()}-${d.getMonth()}`);if(row)row[x.isIncome?"gelir":"gider"]+=Number(x.amount)});return months},[items]);const income=items.filter(x=>x.isIncome).reduce((s,x)=>s+Number(x.amount),0),expense=items.filter(x=>!x.isIncome).reduce((s,x)=>s+Number(x.amount),0),average=items.length?(income+expense)/items.length:0;return <section className="finance-overview"><BasicCard title="6 aylık finans hareketi" subtitle="Gelir ve giderlerinin zaman içindeki değişimi"><div className="chart-wrap"><ResponsiveContainer width="100%" height={260}><AreaChart data={data}><defs><linearGradient id="incomeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#18ac8e" stopOpacity=".35"/><stop offset="1" stopColor="#18ac8e" stopOpacity="0"/></linearGradient><linearGradient id="expenseFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ec6473" stopOpacity=".3"/><stop offset="1" stopColor="#ec6473" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="4 4"/><XAxis dataKey="name" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip formatter={money}/><Area type="monotone" dataKey="gelir" stroke="#18ac8e" fill="url(#incomeFill)" strokeWidth={3}/><Area type="monotone" dataKey="gider" stroke="#ec6473" fill="url(#expenseFill)" strokeWidth={3}/></AreaChart></ResponsiveContainer>{!items.length&&<div className="chart-empty">İlk işlemini eklediğinde finans grafiğin burada oluşacak.</div>}</div></BasicCard><aside className="monthly-summary"><h3>Aylık özet</h3><p>Finansal hareketlerinin kısa görünümü</p><div><span>Günlük ortalama</span><b>{money(average/30)}</b></div><div><span>İşlem ortalaması</span><b>{money(average)}</b></div><div><span>Net değişim</span><b className={income-expense>=0?"good":"warn"}>{money(income-expense)}</b></div><NavLink to="/istatistikler">Detaylı analizi aç →</NavLink></aside></section>}
function MonthlyFinancialOverview({items}){const now=new Date(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(),monthItems=items.filter(x=>{const d=new Date(x.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}),data=useMemo(()=>{const rows=Array.from({length:days},(_,i)=>({name:String(i+1),gelir:0,gider:0}));monthItems.forEach(x=>{const d=new Date(x.date);rows[d.getDate()-1][x.isIncome?"gelir":"gider"]+=Number(x.amount)});return rows},[monthItems,days]);const income=monthItems.filter(x=>x.isIncome).reduce((s,x)=>s+Number(x.amount),0),expense=monthItems.filter(x=>!x.isIncome).reduce((s,x)=>s+Number(x.amount),0),average=monthItems.length?(income+expense)/monthItems.length:0;return <section className="finance-overview"><BasicCard title="Aylık finans hareketi" subtitle={`${now.toLocaleDateString("tr-TR",{month:"long",year:"numeric"})} · günlük gelir ve giderler`}><div className="chart-wrap"><ResponsiveContainer width="100%" height={260}><AreaChart data={data}><CartesianGrid vertical={false} strokeDasharray="4 4"/><XAxis dataKey="name" interval={4} axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip labelFormatter={v=>`${v} ${now.toLocaleDateString("tr-TR",{month:"long"})}`} formatter={money}/><Area type="monotone" dataKey="gelir" name="Gelir" stroke="#18ac8e" fill="#18ac8e22" strokeWidth={3}/><Area type="monotone" dataKey="gider" name="Gider" stroke="#ec6473" fill="#ec647322" strokeWidth={3}/></AreaChart></ResponsiveContainer>{!monthItems.length&&<div className="chart-empty">Bu ay ilk işlemini eklediğinde finans grafiğin burada oluşacak.</div>}</div></BasicCard><aside className="monthly-summary"><h3>Bu ayın özeti</h3><p>{now.toLocaleDateString("tr-TR",{month:"long",year:"numeric"})}</p><div><span>Günlük ortalama</span><b>{money((income+expense)/days)}</b></div><div><span>İşlem ortalaması</span><b>{money(average)}</b></div><div><span>Net değişim</span><b className={income-expense>=0?"good":"warn"}>{money(income-expense)}</b></div><NavLink to="/istatistikler">Detaylı analizi aç →</NavLink></aside></section>}
function SelectedSavingsGoals(){const user=getUser(),key=`saving-goals-${user.userId||user.email||"guest"}`,[goals,setGoals]=useState(()=>{try{const a=JSON.parse(localStorage.getItem(key));return Array.isArray(a)?a:[]}catch{return[]}}),[selectedId,setSelectedId]=useState(null),[showForm,setShowForm]=useState(false),[draft,setDraft]=useState({name:"",target:""}),[amount,setAmount]=useState("");const selected=goals.find(g=>g.id===selectedId)||goals[0],persist=list=>{setGoals(list);localStorage.setItem(key,JSON.stringify(list));if(list.length&&!list.some(g=>g.id===selectedId))setSelectedId(list[0].id)},create=e=>{e.preventDefault();if(!draft.name.trim()||!Number(draft.target))return;const goal={id:Date.now(),name:draft.name.trim(),target:Number(draft.target),current:0};persist([...goals,goal]);setSelectedId(goal.id);setDraft({name:"",target:""});setShowForm(false)},add=()=>{const n=Number(amount)||0;if(!selected||n<=0)return;persist(goals.map(g=>g.id===selected.id?{...g,current:g.current+n}:g));setAmount("")},remove=()=>{if(selected&&confirm("Bu hedef silinsin mi?"))persist(goals.filter(g=>g.id!==selected.id))};const rate=selected?Math.min(100,Math.round(selected.current/selected.target*100)):0;return <BasicCard title="Birikim hedeflerim" subtitle="Listeden bir hedef seçerek ilerlemeni görüntüle"><div className="goal-selector"><label>Hedeflerim<select value={selected?.id||""} onChange={e=>setSelectedId(Number(e.target.value))}>{goals.length?<>{goals.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</>:<option value="">Henüz hedef yok</option>}</select></label><button className="primary" onClick={()=>setShowForm(!showForm)}>+ Yeni hedef</button></div>{showForm&&<form className="new-goal-form compact" onSubmit={create}><input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Örn. Telefon"/><CurrencyInput label="Hedef tutarı" value={draft.target} onChange={v=>setDraft({...draft,target:v})} placeholder="30.000"/><button>Oluştur</button></form>}{selected?<article className="selected-goal"><div className="goal-ring small" style={{"--goal":`${rate*3.6}deg`}}><div><strong>%{rate}</strong><small>{money(selected.current)}</small></div></div><div className="goal-info"><span>SEÇİLİ HEDEF</span><h3>{selected.name}</h3><p><b>{money(selected.current)}</b> birikti · {money(Math.max(0,selected.target-selected.current))} kaldı</p><div className="goal-bar"><i style={{width:`${rate}%`}}/></div><div className="contribution"><CurrencyInput label="Birikime eklenecek tutar" value={amount} onChange={setAmount} placeholder="Biriken para ekle"/><button onClick={add}>Ekle</button><button className="delete-goal" onClick={remove}>Sil</button></div></div></article>:<div className="goal-empty"><span>◎</span><b>Henüz birikim hedefin yok</b><small>“Yeni hedef” düğmesiyle ilk hedefini oluşturabilirsin.</small></div>}</BasicCard>}
function MonthlyOverviewV2({items}){const now=new Date(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate(),monthItems=items.filter(x=>{const d=new Date(x.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});const data=Array.from({length:days},(_,i)=>({name:String(i+1),gelir:0,gider:0}));monthItems.forEach(x=>{const d=new Date(x.date);data[d.getDate()-1][x.isIncome?"gelir":"gider"]+=Number(x.amount)});const income=monthItems.filter(x=>x.isIncome).reduce((s,x)=>s+Number(x.amount),0),expense=monthItems.filter(x=>!x.isIncome).reduce((s,x)=>s+Number(x.amount),0),average=monthItems.length?(income+expense)/monthItems.length:0;return <section className="finance-overview"><BasicCard title="Aylık finans hareketi" subtitle={`${now.toLocaleDateString("tr-TR",{month:"long",year:"numeric"})} · günlük gelir ve giderler`}><div className="chart-wrap v2"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{top:8,right:12,left:0,bottom:24}}><CartesianGrid vertical={false} strokeDasharray="4 4"/><XAxis dataKey="name" interval={4} axisLine={false} tickLine={false} tickMargin={10}/><YAxis axisLine={false} tickLine={false}/><Tooltip labelFormatter={v=>`${v} ${now.toLocaleDateString("tr-TR",{month:"long"})}`} formatter={money}/><Area type="monotone" dataKey="gelir" name="Gelir" stroke="#18ac8e" fill="#18ac8e22" strokeWidth={3}/><Area type="monotone" dataKey="gider" name="Gider" stroke="#ec6473" fill="#ec647322" strokeWidth={3}/></AreaChart></ResponsiveContainer>{!monthItems.length&&<div className="chart-empty">Bu ay ilk işlemini eklediğinde finans grafiğin burada oluşacak.</div>}</div></BasicCard><aside className="monthly-summary"><h3>Bu ayın özeti</h3><p>{now.toLocaleDateString("tr-TR",{month:"long",year:"numeric"})}</p><div><span>Günlük ortalama</span><b>{money((income+expense)/days)}</b></div><div><span>İşlem ortalaması</span><b>{money(average)}</b></div><div><span>Net değişim</span><b className={income-expense>=0?"good":"warn"}>{money(income-expense)}</b></div><NavLink to="/istatistikler">Detaylı analizi aç →</NavLink></aside></section>}
function Empty({text}){return <div className="empty"><span>◇</span><p>{text}</p><small>Yeni kayıtlar eklendikçe bu alan otomatik olarak dolacak.</small></div>}
function Loading(){return <div className="loading"><i/><span>Veriler yükleniyor...</span></div>}
function Layout(){const [dark,setDark]=useState(()=>localStorage.getItem("theme")==="dark");useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("theme",dark?"dark":"light")},[dark]);return <><AppLayoutInternal/><button className="theme-toggle" onClick={()=>setDark(!dark)} title="Temayı değiştir">{dark?"☀":"☾"}</button><nav className="mobile-nav"><NavLink to="/" end>⌂<small>Ana Sayfa</small></NavLink><NavLink to="/islemler">↕<small>İşlemler</small></NavLink><NavLink to="/istatistikler">⌁<small>Analiz</small></NavLink><NavLink to="/kategoriler">▦<small>Kategori</small></NavLink></nav></>}
function Protected(){return (localStorage.getItem("token")||sessionStorage.getItem("token"))?<Layout/>:<Navigate to="/login" replace/>}
export default function App(){const signedIn=localStorage.getItem("token")||sessionStorage.getItem("token");return <BrowserRouter><Routes><Route path="/login" element={signedIn?<Navigate to="/"/>:<Auth mode="login"/>}/><Route path="/register" element={signedIn?<Navigate to="/"/>:<Auth mode="register"/>}/><Route path="/*" element={<Protected/>}/></Routes></BrowserRouter>}
